#!/usr/bin/env bash
#
# Tazkiyah — WhatsApp Cloud API Setup Wizard
# Walks you through Meta Developer Console to connect your Business number.
# Generated by the /wizard skill.
#
# Run with:  bash scripts/setup_whatsapp.sh
#

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library (do not edit)
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-apps/api/.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() { [[ -t 1 ]] || return 0; if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi; }

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()     { printf '  %s\n' "$1"; }
step()    { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note()    { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn()    { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
success() { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser; visit manually: $url"
}

pause() { printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"; read -r _ || true; }

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  mkdir -p "$(dirname "$ENV_FILE")"
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  success "wrote $key → $ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ WhatsApp setup complete!%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "Wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n%sNext steps:%s\n' "$BOLD" "$RESET"
  note "  1. Start the Cloudflare tunnel:  bash scripts/start_tunnel.sh"
  note "  2. Paste the tunnel HTTPS URL into the Meta Webhook URL field"
  note "  3. Start FastAPI:  cd apps/api && .venv/bin/uvicorn app.main:app --port 8000 --reload"
  note "  4. Text your business number from any WhatsApp account to test"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Tazkiyah — WhatsApp Cloud API Setup"

# ── Stage 1: Pre-flight check ──────────────────────────────────────────────
stage "Pre-flight: Migrate your WhatsApp Business number"
say ""
warn "IMPORTANT: Your number is currently on WhatsApp Business App."
warn "The Cloud API and the Business App CANNOT share the same number."
say ""
say "You need to delete the account from the WhatsApp Business App first."
say "Your chat HISTORY stays on device — only the API connection is removed."
say ""
step "Open WhatsApp Business App on your phone."
step "Go to: ⋮ Menu → Settings → Account → Delete my account."
step "Select your country, enter your number, tap DELETE MY ACCOUNT."
step "Confirm the deletion. The number is now free to use with the Cloud API."
say ""
warn "DO NOT uninstall the app yet — just delete the account inside it."
pause "Done deleting the WhatsApp Business account? Press Enter to continue…"

# ── Stage 2: Meta Business Account ────────────────────────────────────────
stage "Meta Business Account"
say "You need a Meta Business Account (free). If you already have one, skip."
say ""
open_url "https://business.facebook.com"
step "Log in with your personal Facebook account."
step "If prompted, create a Business Account with your business name."
step "Once inside Meta Business Suite, note your Business Manager URL."
say ""
pause "You're inside Meta Business Suite. Press Enter to continue…"

# ── Stage 3: Create Meta Developer App ────────────────────────────────────
stage "Meta Developer App"
say "Create a new app in Meta Developers — this is the API entry point."
say ""
open_url "https://developers.facebook.com/apps/create/"
step "Click 'Business' as the app type, then Next."
step "App name: Tazkiyah Finance (or anything you like)."
step "Business Account: select the one you just set up."
step "Click 'Create App'."
say ""
pause "App created. Press Enter to continue…"

# ── Stage 4: Add WhatsApp Product ─────────────────────────────────────────
stage "Add WhatsApp to your App"
say "Inside your new app, add the WhatsApp product."
say ""
step "On the app dashboard, scroll down to 'Add a product'."
step "Find 'WhatsApp' and click 'Set up'."
step "You'll be taken to the WhatsApp Getting Started page."
step "Under 'Step 1: Select phone numbers' → click 'Add phone number'."
step "Enter your country code and phone number (the one you just freed up)."
step "Meta will send an OTP SMS to that number — enter it to verify."
say ""
pause "Phone number verified and added. Press Enter to continue…"

# ── Stage 5: Collect credentials ──────────────────────────────────────────
stage "Collect API credentials"
say "Now collect the three values Tazkiyah needs."
say ""
step "On the WhatsApp Getting Started page, find 'Step 2: Send messages'."
step "You'll see a box labelled 'From' — it shows your Phone Number ID."
open_url "https://developers.facebook.com/apps/"
say ""
ask WHATSAPP_PHONE_NUMBER_ID "Phone Number ID (numbers only, e.g. 123456789012345):"
say ""
step "Scroll up to 'Temporary access token' — click 'Copy' next to it."
note "(This token expires in 24h. In Stage 7 we'll set up a permanent System User token.)"
say ""
ask_secret WHATSAPP_TOKEN "Paste the Temporary Access Token (starts with EAAG or EAA):"
say ""
say "Now choose your webhook verify token — any secret string you like."
say "(You'll paste this into Meta in the next stage.)"
ask WHATSAPP_VERIFY_TOKEN "Choose a verify token (e.g. tazkiyah_whatsapp_2024):"
say ""
write_env WHATSAPP_PHONE_NUMBER_ID "$WHATSAPP_PHONE_NUMBER_ID"
write_env WHATSAPP_TOKEN "$WHATSAPP_TOKEN"
write_env WHATSAPP_VERIFY_TOKEN "$WHATSAPP_VERIFY_TOKEN"

# ── Stage 6: Cloudflare Tunnel ────────────────────────────────────────────
stage "Cloudflare Tunnel (free public HTTPS URL)"
say "Meta needs a public HTTPS URL to deliver WhatsApp messages."
say "Cloudflare Tunnel gives you one for free, permanently."
say ""
step "Install cloudflared if you don't have it:"
note "  curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared"
say ""
step "Run a quick test tunnel to get a temporary URL right now:"
note "  cloudflared tunnel --url http://localhost:8000"
note "  (It will print a URL like: https://xxxx.trycloudflare.com)"
say ""
step "For a permanent URL, log in and create a named tunnel:"
open_url "https://one.dash.cloudflare.com/"
note "  cloudflared login"
note "  cloudflared tunnel create tazkiyah"
note "  cloudflared tunnel route dns tazkiyah api.yourdomain.com"
say ""
say "For now, copy the temporary trycloudflare.com URL for the next step."
ask CLOUDFLARE_URL "Paste your Cloudflare tunnel URL (e.g. https://xxxx.trycloudflare.com):"
say ""
note "Webhook URL to use in Meta: ${CLOUDFLARE_URL}/api/v1/webhook/whatsapp"
pause "Got the URL. Press Enter to configure the webhook in Meta…"

# ── Stage 7: Configure Webhook in Meta ────────────────────────────────────
stage "Register the webhook with Meta"
say "Tell Meta where to deliver WhatsApp messages."
say ""
WEBHOOK_URL="${CLOUDFLARE_URL}/api/v1/webhook/whatsapp"
step "In your Meta App dashboard, go to: WhatsApp → Configuration."
open_url "https://developers.facebook.com/apps/"
step "Under 'Webhook', click 'Edit'."
step "Callback URL:  ${WEBHOOK_URL}"
step "Verify token:  ${WHATSAPP_VERIFY_TOKEN}"
step "Click 'Verify and Save'."
note "(FastAPI must be running on port 8000 with the tunnel active for this to succeed.)"
say ""
step "After saving, click 'Manage' next to Webhook."
step "Subscribe to the 'messages' field — click the toggle."
say ""
pause "Webhook registered and 'messages' subscribed. Press Enter to finish…"

finish
